# Generated by Django 3.1 on 2020-08-17 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200818_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=250)),
                ('take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.hottake')),
            ],
        ),
    ]
