# Generated by Django 3.1 on 2020-08-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='hottake',
            name='sourced',
            field=models.ManyToManyField(to='core.Source'),
        ),
    ]
