# Generated by Django 3.1 on 2020-08-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_hottake_sourced'),
    ]

    operations = [
        migrations.AddField(
            model_name='hottake',
            name='opinion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hottake',
            name='sourced',
            field=models.ManyToManyField(related_name='sourced', to='core.Source'),
        ),
    ]
